Repository HipsterDave/The-Legend-of-Talera, pull requests merged in 2020-12, with the labels that each got.

#10 Tested using Github with VScode.
  main.py
Labels: test

#12 Added a feature so that the clear function works on all platforms.
  __pycache__/functions.cpython-38.pyc
  __pycache__/game.cpython-38.pyc
  __pycache__/levels.cpython-38.pyc
  __pycache__/text.cpython-38.pyc
  functions.py
  game.py
  levels.py
Labels: fixed bug

#15 Added the SURPRISE feature. (The City)
  __pycache__/city.cpython-38.pyc
  __pycache__/functions.cpython-38.pyc
  __pycache__/game.cpython-38.pyc
  __pycache__/levels.cpython-38.pyc
  __pycache__/text.cpython-38.pyc
  city.py
  levels.py
  text.py
Labels: added feature, bulletin board, needs reviewers

#19 added mountains level
  levels.py
  text.py
Labels: added feature, needs reviewers, story

#20 Update README.md
  README.md
Labels: improved existing, readme

#21 added os.system("cls") to the beginning of main.py
  __pycache__/city.cpython-38.pyc
  __pycache__/functions.cpython-38.pyc
  __pycache__/game.cpython-38.pyc
  __pycache__/levels.cpython-38.pyc
  __pycache__/text.cpython-38.pyc
  game.py
  main.py
  text.py
Labels: improved existing

#22 Added feature to city.py where if you don't have enough coins for something, it tells you how many coins you are short.
  __pycache__/city.cpython-38.pyc
  __pycache__/game.cpython-38.pyc
  __pycache__/text.cpython-38.pyc
  city.py
Labels: added feature, improved existing

#23 Fixed bug in trophy room
  __pycache__/city.cpython-38.pyc
  __pycache__/levels.cpython-38.pyc
  city.py
  levels.py
Labels: fixed bug
